### ISSUE TITLE
[Types] Missing class property in HTMLAttributes definition

### ISSUE THREAD

**Issue by amoutonbrady** [ryansolid/babel-plugin-jsx-dom-expressions#34]
Hey there, first and foremost thanks for making that library (and the ecosystem around it, especially Solid). Working with it for a small internal project has been delightful.

I use VSCode as my main code editor and being based on TS, it automatically lint JS files, which is quite useful because you then have access to all the autosuggestions, etc.

In the latest release you improved a lot on the typing for the custom control flow elements. I was having quite some errors there. They are now gone! Thank you.

There's just a last little thing that's been bothering me. As the title say, in the types there are no definition for the `class` attribute on `HTMLAttributes`. I was wondering if it would be possible to add it or if that was intentional?

[Here's the part where I think it should be](https://github.com/ryansolid/babel-plugin-jsx-dom-expressions/blob/master/types/index.d.ts#L445) next to `className`.

Anyway, keep rocking!

**Comment by ryansolid** [comment]
Thanks for pointing this out. `for` was missing too. Fixed in v0.15.1.
